export enum ContentType {
    JSON = "application/json",
    HTML = "text/html",
    PlainText = "text/plain",
    XML = "application/xml",
    FormURLEncoded = "application/x-www-form-urlencoded",
    MultipartFormData = "multipart/form-data",
    JavaScript = "application/javascript",
    CSS = "text/css",
    CSV = "text/csv",
    JPEG = "image/jpeg",
    PNG = "image/png",
    GIF = "image/gif",
    WebP = "image/webp",
    SVG = "image/svg+xml",
    ICO = "image/x-icon",
    PDF = "application/pdf",
    ZIP = "application/zip",
    GZIP = "application/gzip",
    OctetStream = "application/octet-stream",
    RTF = "application/rtf",
    OGG = "application/ogg",
    MP3 = "audio/mpeg",
    MPEG = "video/mpeg",
    MP4 = "video/mp4",
    WebM = "video/webm",
}
